#!/bin/sh

abs_top_srcdir="/home/nalaginrut/Project/hardenedlinux/SonicCross"
abs_top_builddir="/home/nalaginrut/Project/hardenedlinux/SonicCross"

GUILE_LOAD_PATH="$abs_top_srcdir:$abs_top_srcdir/modules${GUILE_LOAD_PATH:+:$GUILE_LOAD_PATH}"
GUILE_LOAD_COMPILED_PATH="$abs_top_builddir:$abs_top_builddir/modules${GUILE_LOAD_COMPILED_PATH:+:$GUILE_LOAD_COMPILED_PATH}"
export GUILE_LOAD_PATH GUILE_LOAD_COMPILED_PATH

exec "$@"
