;;  -*-  indent-tabs-mode:nil; coding: utf-8 -*-
;;  Copyright (C) 2026
;;      "Mu Lei" known as "NalaGinrut" <roy@hardenedlinux.org>
;;  SonicCross is free software: you can redistribute it and/or modify
;;  it under the terms of the GNU General Public License published
;;  by the Free Software Foundation, either version 3 of the License,
;;  or (at your option) any later version.

;;  SonicCross is distributed in the hope that it will be useful,
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;;  GNU General Public License for more details.

;;  You should have received a copy of the GNU General Public License
;;  along with this program. If not, see <http://www.gnu.org/licenses/>.

;; Core-sources emitters (gen.py gen_headers / gen_source_files tail):
;;
;;   G18  aten_interned_strings.h  (gen_aten_interned_strings)
;;        enum_tag.h               (gen_tags_enum)
;;   G19  TensorMethods.cpp        (verbatim template write)
;;        ATenOpList.cpp           (compute_aten_op)
;;
;; All byte-identical against frozen torchgen 41ffbc4a994e058af9fe00ed5caba73fc1033359.

(define-module (sonic-cross core-sources)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-13)
  #:use-module (sonic-cross core-ir)
  #:use-module (sonic-cross native-function)
  #:use-module (sonic-cross generated-functions)
  #:use-module (sonic-cross code-template)
  #:export (render-aten-interned-strings-h
            render-enum-tag-h
            render-tensor-methods-cpp
            render-aten-op-list-cpp))

(define %generator-path "torchgen/gen.py")

;; C++ alternative-operator keywords, which are not valid symbol names.
;; https://en.cppreference.com/w/cpp/language/operator_alternative
(define cpp-keywords
  '("and" "and_eq" "bitand" "bitor" "compl" "not" "not_eq" "or" "or_eq"
    "xor" "xor_eq"))

;; ---------------------------------------------------------------------------
;; G18a: aten_interned_strings.h
;; ---------------------------------------------------------------------------

(define %aten-interned-strings-template
  (string-append
   "#pragma once\n"
   "\n"
   "// ${generated_comment}\n"
   "\n"
   "#if defined(TORCH_ASSERT_NO_OPERATORS) || defined(TORCH_ASSERT_ONLY_METHOD_OPERATORS)\n"
   "#error This change adds a dependency on native_functions.yaml,          \\\n"
   "  meaning the file will need to be re-compiled every time an operator   \\\n"
   "  is changed or added. Consider if including <ATen/core/symbol.h> for   \\\n"
   "  the c10::Symbol class would be sufficient, or if your change would be \\\n"
   "  better placed in another file.\n"
   "#endif\n"
   "\n"
   "// ATen symbols correspond exactly to operators defined in ATen. Every\n"
   "// symbol here corresponds exactly to an ATen operation defined in\n"
   "// native_functions.yaml; attributes are in one-to-one correspondence\n"
   "// with their ATen name.\n"
   "\n"
   "#define FORALL_ATEN_BASE_SYMBOLS(_) \\\n"
   "${aten_symbols}\n"
   "\n"
   "#define FORALL_ATTR_BASE_SYMBOLS(_) \\\n"
   "${attr_symbols}\n"))

(define (render-aten-interned-strings-h functions)
  ;; Mirrors gen_aten_interned_strings(): collect the operator base spellings
  ;; (str(BaseOperatorName) and BaseOperatorName.base) and every schema-order
  ;; argument name, drop the C++ alternative-operator keywords, and render the
  ;; sorted symbols with `_` backslash-continuation joins.
  (let ((names '())
        (attrs '()))
    (for-each
     (lambda (f)
       (let* ((func (native-function-func f))
              (op-name (function-schema-name func)))
         (set! names (cons (base-operator-spelling func) names))
         (set! names
               (cons (base-operator-name-base (operator-name-base op-name))
                     names))
         (set! attrs
               (append (map argument-name
                            (arguments-all (function-schema-arguments func)))
                       attrs))))
     functions)
    (let* ((names (sort (delete-duplicates names string=?) string<?))
           (names (filter (lambda (n) (not (member n cpp-keywords))) names))
           (attrs (sort (delete-duplicates attrs string=?) string<?))
           (aten-symbols
            (string-join (map (lambda (n) (string-append "_(aten, " n ")"))
                              names)
                         " \\\n"))
           (attr-symbols
            (string-join (map (lambda (n) (string-append "_(attr, " n ")"))
                              attrs)
                         " \\\n")))
      (code-template-substitute
       %aten-interned-strings-template
       (lambda (key)
         (cond
          ((string=? key "generated_comment")
           (string-append "@generated by " %generator-path
                          " from aten_interned_strings.h"))
          ((string=? key "aten_symbols") aten-symbols)
          ((string=? key "attr_symbols") attr-symbols)
          (else (error 'unknown-template-key key))))))))

;; ---------------------------------------------------------------------------
;; G18b: enum_tag.h
;; ---------------------------------------------------------------------------

(define %enum-tag-template
  (string-append
   "#pragma once\n"
   "\n"
   "// ${generated_comment}\n"
   "\n"
   "#include <torch/headeronly/macros/Macros.h>\n"
   "\n"
   "HIDDEN_NAMESPACE_BEGIN(torch, headeronly)\n"
   "\n"
   "// Enum of valid tags obtained from the entries in tags.yaml\n"
   "enum class Tag {\n"
   "    ${enum_of_valid_tags}\n"
   "};\n"
   "\n"
   "HIDDEN_NAMESPACE_END(torch, headeronly)\n"
   "\n"
   "// Re-expose in the at:: namespace for backward compatibility\n"
   "namespace at {\n"
   "    using torch::headeronly::Tag;\n"
   "}\n"))

(define (render-enum-tag-h)
  ;; Mirrors gen_tags_enum(): sorted valid tags joined with ",\n".
  (let ((enum-of-valid-tags (string-join (sort valid-tags string<?) ",\n")))
    (code-template-substitute
     %enum-tag-template
     (lambda (key)
       (cond
        ((string=? key "generated_comment")
         (string-append "@generated by " %generator-path " from enum_tag.h"))
        ((string=? key "enum_of_valid_tags") enum-of-valid-tags)
        (else (error 'unknown-template-key key)))))))

;; ---------------------------------------------------------------------------
;; G19a: TensorMethods.cpp (verbatim template, empty env)
;; ---------------------------------------------------------------------------

(define %tensor-methods-template
  (string-append
   "#include <c10/core/Scalar.h>\n"
   "#include <ATen/core/TensorBody.h>\n"
   "#include <torch/headeronly/core/Dispatch_v2.h>\n"
   "\n"
   "#include <string_view>\n"
   "\n"
   "namespace at {\n"
   "\n"
   "namespace {\n"
   "\n"
   "// Verifies the requested type is the same as the Tensor's type.\n"
   "void check_type(const TensorBase& tensor, ScalarType type) {\n"
   "  TORCH_CHECK(\n"
   "      tensor.scalar_type() == type\n"
   "      || (isQIntType(tensor.scalar_type())\n"
   "          && toUnderlying(tensor.scalar_type()) == type),\n"
   "      \"expected scalar type \", type, \" but found \", tensor.scalar_type());\n"
   "}\n"
   "\n"
   "} // namespace\n"
   "\n"
   "template <typename T>\n"
   "const T* TensorBase::const_data_ptr() const {\n"
   "  using NonConstT = std::remove_const_t<T>;\n"
   "  check_type(*this, c10::CppTypeToScalarType<NonConstT>());\n"
   "  return this->unsafeGetTensorImpl()->data_ptr_impl<NonConstT>();\n"
   "}\n"
   "\n"
   "template <typename T>\n"
   "T* TensorBase::mutable_data_ptr() const {\n"
   "  check_type(*this, c10::CppTypeToScalarType<T>());\n"
   "  return this->unsafeGetTensorImpl()->mutable_data_ptr_impl<T>();\n"
   "}\n"
   "\n"
   "template <typename T>\n"
   "T* TensorBase::data_ptr() const {\n"
   "  return this->mutable_data_ptr<T>();\n"
   "}\n"
   "\n"
   "#define DEFINE_CAST(T, name)                                                \\\n"
   "   template TORCH_API const T* TensorBase::const_data_ptr<T>() const;       \\\n"
   "   template TORCH_API const T* TensorBase::const_data_ptr<const T>() const; \\\n"
   "   template TORCH_API T* TensorBase::mutable_data_ptr() const;              \\\n"
   "   template TORCH_API T* TensorBase::data_ptr() const;\n"
   "\n"
   " AT_FORALL_SCALAR_TYPES_V2(\n"
   "   AT_WRAP(DEFINE_CAST),\n"
   "   AT_EXPAND(AT_ALL_SCALAR_TYPES_WITH_COMPLEX),\n"
   "   kUInt16,\n"
   "   kUInt32,\n"
   "   kUInt64)\n"
   " AT_FORALL_QINT_TYPES(DEFINE_CAST)\n"
   " #undef DEFINE_CAST\n"
   "\n"
   " #define DEFINE_ITEM(T, name)      \\\n"
   "   template <>                     \\\n"
   "   TORCH_API T Tensor::item() const { \\\n"
   "     return item().to<T>();     \\\n"
   "   }\n"
   "\n"
   "   AT_FORALL_SCALAR_TYPES_V2(\n"
   "     AT_WRAP(DEFINE_ITEM),\n"
   "     AT_EXPAND(AT_ALL_SCALAR_TYPES_WITH_COMPLEX))\n"
   " #undef DEFINE_ITEM\n"
   "\n"
   " } //namespace at\n"))

(define (render-tensor-methods-cpp)
  ;; core_fm.write("TensorMethods.cpp", dict): the template carries no
  ;; placeholders, so the artifact is the verbatim template.
  %tensor-methods-template)

;; ---------------------------------------------------------------------------
;; G19b: ATenOpList.cpp
;; ---------------------------------------------------------------------------

(define %aten-op-list-template
  (string-append
   "#include <ATen/core/ATenOpList.h>\n"
   "\n"
   "#include <string>\n"
   "#include <cstring>\n"
   "#include <utility>\n"
   "#include <unordered_set>\n"
   "#include <ATen/core/operator_name.h>\n"
   "\n"
   "// ${generated_comment}\n"
   "\n"
   "namespace at {\n"
   "\n"
   "namespace {\n"
   "struct OpNameEquals final {\n"
   "  bool operator()(const std::pair<const char*, const char*>& lhs, const std::pair<const char*, const char*>& rhs) const {\n"
   "      return 0 == strcmp(lhs.first, rhs.first) && 0 == strcmp(lhs.second, rhs.second);\n"
   "  }\n"
   "};\n"
   "\n"
   "struct OpNameHash final {\n"
   "  size_t operator()(const std::pair<const char*, const char*>& p) const {\n"
   "      // use std::hash<std::string> because std::hash<const char*> would hash pointers and not pointed-to strings\n"
   "      return std::hash<std::string>()(p.first) ^ (~ std::hash<std::string>()(p.second));\n"
   "  }\n"
   "};\n"
   "}\n"
   "\n"
   "bool is_custom_op(const c10::OperatorName& opName) {\n"
   "  static std::unordered_set<std::pair<const char*, const char*>, OpNameHash, OpNameEquals> ops {\n"
   "    ${aten_ops}\n"
   "    {\"\", \"\"}\n"
   "  };\n"
   "  return ops.count(std::make_pair(\n"
   "             opName.name.c_str(), opName.overload_name.c_str())) == 0;\n"
   "}\n"
   "}\n"))

(define (compute-aten-op f)
  ;; Mirrors compute_aten_op: `{"aten::{str(BaseOperatorName)}", "{overload}"},`.
  (let* ((func (native-function-func f))
         (name (function-schema-name func)))
    (string-append "{\"aten::" (base-operator-spelling func) "\", \""
                   (operator-name-overload-name name) "\"},")))

(define (render-aten-op-list-cpp functions)
  (code-template-substitute
   %aten-op-list-template
   (lambda (key)
     (cond
      ((string=? key "generated_comment")
       (string-append "@generated by " %generator-path " from ATenOpList.cpp"))
      ((string=? key "aten_ops") (map compute-aten-op functions))
      (else (error 'unknown-template-key key))))))
