;;  -*-  indent-tabs-mode:nil; coding: utf-8 -*-
;;  Copyright (C) 2026
;;      "Mu Lei" known as "NalaGinrut" <roy@hardenedlinux.org>
;;  SonicCross is free software: you can redistribute it and/or modify
;;  it under the terms of the GNU General Public License published
;;  by the Free Software Foundation, either version 3 of the License,
;;  or (at your option) any later version.

;;  SonicCross is distributed in the hope that it will be useful,
;;  but WITHOUT ANY WARRANTY; without even the implied warranty of
;;  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
;;  GNU General Public License for more details.

;;  You should have received a copy of the GNU General Public License
;;  along with this program. If not, see <http://www.gnu.org/licenses/>.

;; The C++ emitter.  This consumes the frozen Semantic IR directly and reproduces
;; the observable output of torchgen's emitters, one generated artifact at a
;; time.  G1 is RegisterSchema.cpp; G2 (Register{key}.cpp) and G3
;; (RegistrationDeclarations.h) follow.  No new IR or serialization format is
;; introduced: templates are embedded verbatim from the frozen commit and the
;; rendered text is the sole output.

(define-module (sonic-cross emitter)
  #:use-module (ice-9 optargs)
  #:use-module (srfi srfi-1)
  #:use-module (srfi srfi-13)
  #:use-module (sonic-cross core-ir)
  #:use-module (sonic-cross native-function)
  #:use-module (sonic-cross dispatcher)
  #:use-module (sonic-cross generated-functions)
  #:use-module (sonic-cross code-template)
  #:use-module ((sonic-cross api) #:prefix api:)
  #:export (cpp-string
            render-register-schema-cpp
            render-registration-declarations-h
            render-method-operators-h
            render-functions-h
            render-functions-cpp
            render-redispatch-functions-h
            render-native-functions-h
            render-native-meta-functions-h
            compute-function
            compute-meta-function-declaration
            compute-native-function-declaration
            get-native-function-declarations
            ordered-backend-indices))

;; The canonical generator path, matching `python3 torchgen/gen.py` at the
;; frozen commit.  The oracle pins its own `__main__.__file__` to this path so
;; the `@generated by ...` prologue is byte-identical.
(define %generator-path "torchgen/gen.py")

(define fragment-namespaces '("quantized" "quantized_decomposed"))

;; ---------------------------------------------------------------------------
;; cpp_string: torchgen gen.cpp_string
;; ---------------------------------------------------------------------------

(define (string-replace-all s target replacement)
  (let loop ((result "") (rest s))
    (let ((idx (string-contains rest target)))
      (if (not idx)
          (string-append result rest)
          (loop (string-append result (substring rest 0 idx) replacement)
                (substring rest (+ idx (string-length target))))))))

(define (cpp-string s)
  ;; Convert a string into a C++ string literal, in torchgen's exact order.
  (let* ((s (string-replace-all s "\\" "\\\\"))
         (s (string-replace-all s "\"" "\\\""))
         (s (string-replace-all s "\a" "\\a"))
         (s (string-replace-all s "\b" "\\b"))
         (s (string-replace-all s "\f" "\\f"))
         (s (string-replace-all s "\n" "\\n"))
         (s (string-replace-all s "\v" "\\v"))
         (s (string-replace-all s "\t" "\\t")))
    (string-append "\"" s "\"")))

;; ---------------------------------------------------------------------------
;; G1: RegisterSchema.cpp
;; ---------------------------------------------------------------------------

(define (register-schema-call f known-tags)
  ;; One native function -> the registration string(s) for it (torchgen
  ;; RegisterSchema.__call__).  `known-tags` is a mutable hash table from the
  ;; canonical tag-set string to its assigned index, shared across the namespace.
  (let* ((tags (sort (native-function-tags f) string<?))
         (tags-str (string-append
                    "{"
                    (string-join
                     (map (lambda (t) (string-append "at::Tag::" t)) tags)
                     ", ")
                    "}")))
    (if (string=? tags-str "{}")
        (string-append
         "m.def("
         (cpp-string (function-schema->string (native-function-func f)))
         ", {});\n")
        (let* ((existing (hash-ref known-tags tags-str #f))
               (idx (if existing existing (hash-count (const #t) known-tags)))
               (maybe-tags
                (if existing
                    ""
                    (begin
                      (hash-set! known-tags tags-str idx)
                      (string-append "const std::vector<at::Tag> tags_"
                                     (number->string idx) " = " tags-str ";\n")))))
          (string-append
           maybe-tags
           "m.def("
           (cpp-string (function-schema->string (native-function-func f)))
           ", tags_" (number->string idx) ");\n")))))

(define (get-native-function-schema-registrations functions)
  ;; Mirrors torchgen gen.get_native_function_schema_registrations.  Returns
  ;; (values aten-registrations custom-schema-registrations), where the former
  ;; is a list of strings (the aten TORCH_LIBRARY body) and the latter is the
  ;; concatenation of any non-aten TORCH_LIBRARY[_FRAGMENT] blocks.
  (let* ((ns-order '())
         (groups (make-hash-table)))
    ;; group by namespace, preserving insertion order
    (for-each
     (lambda (f)
       (let* ((ns (native-function-namespace f))
              (existing (hash-ref groups ns #f)))
         (unless existing (set! ns-order (append ns-order (list ns))))
         (hash-set! groups ns (append (or existing '()) (list f)))))
     functions)
    (let loop ((ns-list ns-order) (aten '()) (custom ""))
      (if (null? ns-list)
          (values aten custom)
          (let* ((ns (car ns-list))
                 (funcs (hash-ref groups ns))
                 (known-tags (make-hash-table))
                 (body (map (lambda (f) (register-schema-call f known-tags))
                            funcs)))
            (if (string=? ns "aten")
                (loop (cdr ns-list) body custom)
                (loop (cdr ns-list)
                      aten
                      (string-append
                       custom
                       "\n" (if (member ns fragment-namespaces)
                                "TORCH_LIBRARY_FRAGMENT"
                                "TORCH_LIBRARY")
                       "(" ns ", m) {\n  "
                       (string-join body "\t")
                       "\n};"))))))))

(define %register-schema-template
  (string-append
   "// ${generated_comment}\n"
   "#define TORCH_ASSERT_ONLY_METHOD_OPERATORS\n"
   "#include <torch/library.h>\n"
   "\n"
   "namespace at {\n"
   "TORCH_LIBRARY(aten, m) {\n"
   "  ${aten_schema_registrations};\n"
   "  // Distributed Ops\n"
   "  // Implementations located in torch/csrc/jit/runtime/register_distributed_ops.cpp\n"
   "  m.def(\"get_gradients(int context_id) -> Dict(Tensor, Tensor)\");\n"
   "}\n"
   "${schema_registrations}\n"
   "}  // namespace at\n"))

(define (render-register-schema-cpp functions)
  (call-with-values
      (lambda () (get-native-function-schema-registrations functions))
    (lambda (aten custom)
      (code-template-substitute
       %register-schema-template
       (lambda (key)
         (cond
          ((string=? key "generated_comment")
           (string-append "@generated by " %generator-path
                          " from RegisterSchema.cpp"))
          ((string=? key "aten_schema_registrations") aten)
          ((string=? key "schema_registrations") custom)
          (else (error 'unknown-template-key key))))))))

;; ---------------------------------------------------------------------------
;; G3: RegistrationDeclarations.h
;; ---------------------------------------------------------------------------

(define %registration-declarations-template
  (string-append
   "// This file contains all native_functions that can be registered to\n"
   "// and the schema string that they should be registered with\n"
   "\n"
   "${registration_declarations}\n"))

(define (render-registration-declarations-h functions)
  (code-template-substitute
   %registration-declarations-template
   (lambda (key)
     (cond
      ((string=? key "registration_declarations")
       (map registration-declaration functions))
      (else (error 'unknown-template-key key))))))

;; ---------------------------------------------------------------------------
;; G4: MethodOperators.h (torchgen gen.py ComputeOperators, DECLARATION branch)
;; ---------------------------------------------------------------------------

(define (method-operator-declaration f)
  ;; One method native function -> the ComputeOperators(Target.DECLARATION)
  ;; struct string.  Mirrors torchgen gen.py ComputeOperators.__call__ with
  ;; static_dispatch_backend_indices == [] (the default flag set).  Each struct
  ;; begins with a newline and ends with "};" (no trailing newline), exactly as
  ;; the torchgen f-string; the block-substitution of the list supplies the
  ;; inter-struct blank lines.
  (let* ((func (native-function-func f))
         (name (unambiguous-name func))
         (use-const-ref (native-function-use-const-ref-for-mutable-tensors? f))
         (use-ilistref (or (native-function-structured? f)
                           (native-function-structured-delegate f))))
    (string-append
     "\nstruct TORCH_API " name " {\n"
     "  using schema = "
     (dispatcher-signature-type func use-const-ref use-ilistref) ";\n"
     "  using ptr_schema = schema*;\n"
     "  // See Note [static constexpr char* members for windows NVCC]\n"
     "  static constexpr const char* name = \"aten::"
     (base-operator-spelling func) "\";\n"
     "  static constexpr const char* overload_name = \""
     (operator-name-overload-name (function-schema-name func)) "\";\n"
     "  static constexpr const char* schema_str = "
     (cpp-string (function-schema->string func)) ";\n"
     "  static "
     (dispatcher-signature-defn func use-const-ref use-ilistref "call" #f) ";\n"
     "  static "
     (dispatcher-signature-defn func use-const-ref use-ilistref "redispatch" #t)
     ";\n"
     "};")))

(define %method-operators-template
  (string-append
   "#pragma once\n"
   "\n"
   "// ${generated_comment}\n"
   "\n"
   "#ifdef TORCH_ASSERT_NO_OPERATORS\n"
   "#error This change adds a dependency on native_functions.yaml,             \\\n"
   "  meaning the file will need to be re-compiled every time an operator      \\\n"
   "  is changed or added. Consider if your change would be better placed in   \\\n"
   "  another file, or if a more specific header might achieve the same goal.  \\\n"
   "  See NOTE: [Tensor vs. TensorBase]\n"
   "#endif\n"
   "\n"
   "// Forward declarations of any types needed in the operator signatures.\n"
   "// We can't directly include these classes because it will cause circular include dependencies.\n"
   "// This file is included by TensorBody.h, which defines the Tensor class.\n"
   "#include <ATen/core/ATen_fwd.h>\n"
   "\n"
   "${MethodOperators_includes}\n"
   "\n"
   "namespace at {\n"
   "namespace _ops {\n"
   "${MethodOperators_declarations}\n"
   "} // namespace _ops\n"
   "} // namespace at\n"))

(define* (render-method-operators-h functions
                                    #:key (includes '()) (declarations #f))
  (let ((method-functions
         (filter (lambda (f) (member "method" (native-function-variants f)))
                 functions)))
    (code-template-substitute
     %method-operators-template
     (lambda (key)
       (cond
        ((string=? key "generated_comment")
         (string-append "@generated by " %generator-path
                        " from MethodOperators.h"))
        ((string=? key "MethodOperators_includes") includes)
        ((string=? key "MethodOperators_declarations")
         (or declarations (map method-operator-declaration method-functions)))
        (else (error 'unknown-template-key key)))))))

;; ---------------------------------------------------------------------------
;; G5: Functions.h (torchgen gen.py ComputeFunction) and Functions.cpp (a
;; verbatim template write).
;; ---------------------------------------------------------------------------

(define (compute-function f)
  ;; One native function -> the ComputeFunction() string for Functions.h.
  ;; Mirrors torchgen gen.py ComputeFunction.__call__ with
  ;; use_const_ref_for_mutable_tensors=f.use_const_ref_for_mutable_tensors and
  ;; use_ilistref_for_tensor_lists=f.part_of_structured_group (the default flag
  ;; set).  Each part begins with a newline: the function declaration has no
  ;; trailing newline while the symint template block ends with one, exactly as
  ;; the torchgen f-strings.  Functions that are neither function-variant nor
  ;; symint yield "".
  (let* ((func (native-function-func f))
         (use-const-ref (api:native-function-use-const-ref-context f))
         (use-ilistref (api:native-function-use-ilistref-context f))
         (has-symint (function-schema-has-symint? func))
         (sigs (api:cpp-signature-group-signatures
                func #t #t (native-function-manual-cpp-binding? f)
                (native-function-cpp-no-default-args f)))
         (function-variant? (member "function" (native-function-variants f)))
         (target-args (api:dispatcher-signature-arguments func #t use-const-ref
                                                          use-ilistref)))
    (string-concatenate
     (map (lambda (sig)
            (let* ((symint (cadddr sig))
                   (exprs (api:translate
                           (api:cpp-signature-arguments sig use-const-ref
                                                        use-ilistref)
                           target-args))
                   (exprs-str (string-join (map api:expr-expr exprs) ", "))
                   (intlike-t (if symint "c10::SymInt" "int64_t"))
                   (unambiguous (unambiguous-name func))
                   (function-part
                    (if function-variant?
                        (string-append
                         "\n// aten::" (function-schema->string func) "\n"
                         "inline "
                         (api:cpp-signature-decl sig use-const-ref use-ilistref)
                         " {\n"
                         "    return at::_ops::" unambiguous "::call("
                         exprs-str ");\n"
                         "}")
                        ""))
                   (symint-part
                    (if has-symint
                        (string-append
                         "\nnamespace symint {\n"
                         "  template <typename T, typename = std::enable_if_t<std::is_same_v<T, "
                         intlike-t ">>>\n"
                         "  "
                         (api:cpp-signature-decl sig use-const-ref use-ilistref
                                                 #:suppress-symint-suffix #t)
                         " {\n"
                         "    return at::_ops::" unambiguous "::call("
                         exprs-str ");\n"
                         "  }\n"
                         "}\n")
                        "")))
              (string-append function-part symint-part)))
          sigs))))

(define %functions-h-template
  (string-append
   "#pragma once\n"
   "\n"
   "// ${generated_comment}\n"
   "\n"
   "#ifdef TORCH_ASSERT_NO_OPERATORS\n"
   "#error This change adds a dependency on native_functions.yaml,            \\\n"
   "  meaning the file will need to be re-compiled every time an operator     \\\n"
   "  is changed or added. Consider if your change would be better placed in  \\\n"
   "  another file, or if a more specific header might achieve the same goal. \\\n"
   "  See NOTE: [Tensor vs. TensorBase]\n"
   "#endif\n"
   "\n"
   "#if defined(AT_PER_OPERATOR_HEADERS) && defined(TORCH_ASSERT_ONLY_METHOD_OPERATORS)\n"
   "#error This change adds a dependency on all pytorch operators, meaning the     \\\n"
   "  file will need to be re-compiled every time an operator is changed or added. \\\n"
   "  Consider including a specific operator from <ATen/ops/{my_operator}.h> and   \\\n"
   "  see NOTE [TORCH_ASSERT_ONLY_METHOD_OPERATORS].\n"
   "#endif\n"
   "\n"
   "// NOTE: [TORCH_ASSERT_ONLY_METHOD_OPERATORS]\n"
   "//\n"
   "// In ATen, certain generated headers files include the definitions of\n"
   "// every single operator in PyTorch. Unfortunately this means every\n"
   "// time an operator signature is updated or changed in\n"
   "// native_functions.yaml, you (and every other PyTorch developer) need\n"
   "// to recompile every source file that includes any of these headers.\n"
   "//\n"
   "// To break up these header dependencies, and improve incremental\n"
   "// build times for all PyTorch developers. These headers are split\n"
   "// into per-operator headers in the `ATen/ops` folder. This limits\n"
   "// incremental builds to only changes to methods of `Tensor`, or files\n"
   "// that use the specific operator being changed. With `at::sum` as an\n"
   "// example, you should include\n"
   "//\n"
   "//   <ATen/ops/sum.h>               // instead of ATen/Functions.h\n"
   "//   <ATen/ops/sum_native.h>        // instead of ATen/NativeFunctions.h\n"
   "//   <ATen/ops/sum_ops.h>           // instead of ATen/Operators.h\n"
   "//   <ATen/ops/sum_cpu_dispatch.h>  // instead of ATen/CPUFunctions.h\n"
   "//\n"
   "// However, even if you're careful to use this in your own code.\n"
   "// `Functions.h` might be included indirectly through another header\n"
   "// without you realising. To avoid this, you can add\n"
   "//\n"
   "//   #define TORCH_ASSERT_ONLY_METHOD_OPERATORS\n"
   "//\n"
   "// to the top of your source file. This way any time the non-specific\n"
   "// headers are included, the compiler will error out.\n"
   "//\n"
   "// Also, be aware that `ops` are not available in all build\n"
   "// configurations (namely fb-internal) so you must guard these\n"
   "// includes with `#ifdef AT_PER_OPERATOR_HEADERS`. e.g.\n"
   "//\n"
   "//   #ifndef AT_PER_OPERATOR_HEADERS\n"
   "//   #include <ATen/Functions.h>\n"
   "//   #else\n"
   "//   #include <ATen/ops/sum.h>\n"
   "//   #endif\n"
   "\n"
   "#include <ATen/Context.h>\n"
   "#include <ATen/DeviceGuard.h>\n"
   "#include <ATen/TensorUtils.h>\n"
   "#include <ATen/TracerMode.h>\n"
   "#include <ATen/core/Generator.h>\n"
   "#include <ATen/core/Reduction.h>\n"
   "#include <c10/core/SymInt.h>\n"
   "#include <ATen/core/Tensor.h>\n"
   "#include <c10/core/Scalar.h>\n"
   "#include <c10/core/Storage.h>\n"
   "#include <c10/core/TensorOptions.h>\n"
   "#include <c10/util/Deprecated.h>\n"
   "#include <optional>\n"
   "#include <c10/util/OptionalArrayRef.h>\n"
   "\n"
   "#include <ATen/ops/from_blob.h>\n"
   "#include <ATen/ops/tensor.h>\n"
   "\n"
   "${Functions_includes}\n"
   "\n"
   "namespace at {\n"
   "\n"
   "${Functions_declarations}\n"
   "\n"
   "// Special C++ only overloads for std()-like functions (See gh-40287)\n"
   "// These are needed because int -> bool conversion takes precedence over int -> IntArrayRef\n"
   "// So, for example std(0) would select the std(unbiased=False) overload\n"
   "inline Tensor var(const Tensor& self, int dim) {\n"
   "  return at::var(self, IntArrayRef{dim});\n"
   "}\n"
   "inline std::tuple<Tensor, Tensor> var_mean(const Tensor& self, int dim) {\n"
   "  return at::var_mean(self, IntArrayRef{dim});\n"
   "}\n"
   "inline Tensor std(const Tensor& self, int dim) {\n"
   "  return at::std(self, IntArrayRef{dim});\n"
   "}\n"
   "inline std::tuple<Tensor, Tensor> std_mean(const Tensor& self, int dim) {\n"
   "  return at::std_mean(self, IntArrayRef{dim});\n"
   "}\n"
   "\n"
   "inline int64_t numel(const Tensor& tensor) {\n"
   "  return tensor.numel();\n"
   "}\n"
   "\n"
   "inline int64_t size(const Tensor& tensor, int64_t dim) {\n"
   "  return tensor.size(dim);\n"
   "}\n"
   "\n"
   "inline int64_t stride(const Tensor& tensor, int64_t dim) {\n"
   "  return tensor.stride(dim);\n"
   "}\n"
   "\n"
   "inline bool is_complex(const Tensor& tensor) {\n"
   "  return tensor.is_complex();\n"
   "}\n"
   "\n"
   "inline bool is_floating_point(const Tensor& tensor) {\n"
   "  return tensor.is_floating_point();\n"
   "}\n"
   "\n"
   "inline bool is_signed(const Tensor& tensor) {\n"
   "  return tensor.is_signed();\n"
   "}\n"
   "\n"
   "inline bool is_inference(const Tensor& tensor) {\n"
   "  return tensor.is_inference();\n"
   "}\n"
   "\n"
   "inline bool _is_zerotensor(const Tensor& tensor) {\n"
   "  return tensor._is_zerotensor();\n"
   "}\n"
   "\n"
   "inline bool is_conj(const Tensor& tensor) {\n"
   "  return tensor.is_conj();\n"
   "}\n"
   "\n"
   "inline Tensor conj(const Tensor& tensor) {\n"
   "  return tensor.conj();\n"
   "}\n"
   "\n"
   "inline bool is_neg(const Tensor& tensor) {\n"
   "  return tensor.is_neg();\n"
   "}\n"
   "\n"
   "}\n"))

(define* (render-functions-h functions
                             #:key (includes '("#include <ATen/Operators.h>"))
                             (declarations #f))
  (code-template-substitute
   %functions-h-template
   (lambda (key)
     (cond
      ((string=? key "generated_comment")
       (string-append "@generated by " %generator-path " from Functions.h"))
      ((string=? key "Functions_includes") includes)
      ((string=? key "Functions_declarations")
       (or declarations (map compute-function functions)))
      (else (error 'unknown-template-key key))))))

(define %functions-cpp-template
  (string-append
   "#include <array>\n"
   "\n"
   "#include <ATen/Functions.h>\n"
   "#include <ATen/Utils.h>\n"
   "#include <c10/core/Allocator.h>\n"
   "\n"
   "namespace at {\n"
   "\n"
   "Tensor TensorMaker::make_tensor() {\n"
   "   AutoDispatchBelowADInplaceOrView guard{}; // TODO: Remove.\n"
   "   tracer::impl::NoTracerDispatchMode tracer_guard{};\n"
   "\n"
   "   check_size_nonnegative(sizes_);\n"
   "\n"
   "   TORCH_CHECK_VALUE(\n"
   "       !deleter_ || !ctx_,\n"
   "       \"The deleter and context arguments are mutually exclusive.\");\n"
   "\n"
   "   if (device_ == std::nullopt) {\n"
   "     device_ = globalContext().getDeviceFromPtr(data_, opts_.device().type());\n"
   "   }\n"
   "\n"
   "   if (opts_.device().has_index()) {\n"
   "     // clang-format off\n"
   "     TORCH_CHECK_VALUE(\n"
   "         opts_.device() == *device_,\n"
   "         \"Specified device \", opts_.device(), \" does not match device of data \", *device_);\n"
   "     // clang-format on\n"
   "   }\n"
   "\n"
   "   std::size_t size_bytes = computeStorageSize();\n"
   "\n"
   "   DataPtr data_ptr{};\n"
   "   if (deleter_) {\n"
   "     data_ptr = makeDataPtrFromDeleter();\n"
   "   } else {\n"
   "     data_ptr = makeDataPtrFromContext();\n"
   "   }\n"
   "\n"
   "   TORCH_CHECK(!resizeable_ || allocator_ != nullptr, \"Must specify an allocator with allocator() if you want to use resizeable_storage()\");\n"
   "   Storage storage{Storage::use_byte_size_t{}, size_bytes, std::move(data_ptr), /*allocator=*/allocator_, /*resizable=*/resizeable_};\n"
   "\n"
   "   Tensor tensor = detail::make_tensor<TensorImpl>(\n"
   "       std::move(storage), opts_.computeDispatchKey(), opts_.dtype());\n"
   "\n"
   "  TensorImpl* tensor_impl = tensor.unsafeGetTensorImpl();\n"
   "  if (strides_) {\n"
   "    tensor_impl->set_sizes_and_strides(sizes_, *strides_);\n"
   "  } else {\n"
   "    tensor_impl->set_sizes_contiguous(sizes_);\n"
   "  }\n"
   "  if (storage_offset_) {\n"
   "    tensor_impl->set_storage_offset(*storage_offset_);\n"
   "  }\n"
   "\n"
   "  tensor_impl->set_requires_grad(opts_.requires_grad());\n"
   "\n"
   "  return tensor;\n"
   " }\n"
   "\n"
   " std::size_t TensorMaker::computeStorageSize() const {\n"
   "   std::size_t itemsize = opts_.dtype().itemsize();\n"
   "\n"
   "   if (strides_) {\n"
   "     auto storage_size = detail::computeStorageNbytes(sizes_, *strides_, itemsize);\n"
   "     if (storage_offset_) {\n"
   "       storage_size += storage_offset_.value() * itemsize;\n"
   "     }\n"
   "     return storage_size;\n"
   "   }\n"
   "\n"
   "   std::size_t size = 1;\n"
   "   for (std::int64_t s : sizes_) {\n"
   "     size *= static_cast<std::size_t>(s);\n"
   "   }\n"
   "   auto storage_size = size * itemsize;\n"
   "   if (storage_offset_) {\n"
   "     storage_size += storage_offset_.value() * itemsize;\n"
   "   }\n"
   "   return storage_size;\n"
   " }\n"
   "\n"
   " inline DataPtr TensorMaker::makeDataPtrFromDeleter() noexcept {\n"
   "   return InefficientStdFunctionContext::makeDataPtr(data_, std::move(deleter_), *device_);\n"
   " }\n"
   "\n"
   " inline DataPtr TensorMaker::makeDataPtrFromContext() noexcept {\n"
   "   return DataPtr{data_, ctx_.release(), ctx_.get_deleter(), *device_};\n"
   " }\n"
   "\n"
   " IntArrayRef TensorMaker::makeTempSizes() const noexcept {\n"
   "   static std::int64_t zeros[5] = {0, 0, 0, 0, 0};\n"
   "   if (opts_.has_memory_format()) {\n"
   "     MemoryFormat format = *opts_.memory_format_opt();\n"
   "     if (format == MemoryFormat::ChannelsLast) {\n"
   "       return IntArrayRef(zeros, 4);\n"
   "     }\n"
   "     if (format == MemoryFormat::ChannelsLast3d) {\n"
   "       return IntArrayRef(zeros, 5);\n"
   "     }\n"
   "   }\n"
   "   return IntArrayRef(zeros, 1);\n"
   " }\n"
   "\n"
   "} // namespace at\n"))

(define (render-functions-cpp)
  ;; Functions.cpp is a verbatim template write (cpu_fm.write("Functions.cpp",
  ;; dict)); no placeholder is substituted.
  %functions-cpp-template)

;; ---------------------------------------------------------------------------
;; G6: RedispatchFunctions.h (torchgen gen.py ComputeRedispatchFunction)
;; ---------------------------------------------------------------------------

(define (compute-redispatch-function f)
  ;; One native function -> the ComputeRedispatchFunction() string.  Unlike
  ;; ComputeFunction this unconditionally emits a function variant (not a
  ;; method) and prepends the dispatchKeySet redispatch argument; there is no
  ;; symint namespace block.
  (let* ((func (native-function-func f))
         (use-const-ref (api:native-function-use-const-ref-context f))
         (use-ilistref (api:native-function-use-ilistref-context f))
         (sigs (api:cpp-signature-group-signatures
                func #t #t (native-function-manual-cpp-binding? f)
                (native-function-cpp-no-default-args f)))
         (target-args (api:dispatcher-signature-arguments func #t use-const-ref
                                                          use-ilistref)))
    (string-concatenate
     (map (lambda (sig)
            (let* ((exprs (api:translate
                           (api:cpp-signature-arguments sig use-const-ref
                                                        use-ilistref)
                           target-args))
                   (exprs-str (string-join
                               (cons "dispatchKeySet" (map api:expr-expr exprs))
                               ", "))
                   (unambiguous (unambiguous-name func)))
              (string-append
               "\n// aten::" (function-schema->string func) "\n"
               "inline "
               (api:cpp-signature-decl sig use-const-ref use-ilistref
                                       #:is-redispatching-fn #t)
               " {\n"
               "    return at::_ops::" unambiguous "::redispatch("
               exprs-str ");\n"
               "}\n")))
          sigs))))

(define %redispatch-functions-template
  (string-append
   "#pragma once\n"
   "\n"
   "// ${generated_comment}\n"
   "\n"
   "#ifdef TORCH_ASSERT_ONLY_METHOD_OPERATORS\n"
   "#error This change adds a dependency on all pytorch operators, meaning the     \\\n"
   "  file will need to be re-compiled every time an operator is changed or added. \\\n"
   "  Consider using the at::_ops::{name}::redispatch() interface by including     \\\n"
   "  the specific operator from <ATen/ops/{my_operator}_ops.h>\n"
   "#endif\n"
   "\n"
   "#include <c10/core/Scalar.h>\n"
   "#include <ATen/Tensor.h>\n"
   "#include <c10/core/Storage.h>\n"
   "#include <ATen/core/Generator.h>\n"
   "#include <c10/util/Deprecated.h>\n"
   "#include <ATen/DeviceGuard.h>\n"
   "#include <c10/core/TensorOptions.h>\n"
   "#include <ATen/core/Reduction.h>\n"
   "#include <optional>\n"
   "#include <ATen/TensorUtils.h>\n"
   "#include <ATen/Context.h>\n"
   "#include <ATen/TracerMode.h>\n"
   "#include <ATen/Operators.h>\n"
   "\n"
   "namespace at {\n"
   "\n"
   "namespace redispatch {\n"
   "    ${function_redispatch_definitions}\n"
   "} // namespace redispatch\n"
   "\n"
   "}\n"))

(define (render-redispatch-functions-h functions)
  (code-template-substitute
   %redispatch-functions-template
   (lambda (key)
     (cond
      ((string=? key "generated_comment")
       (string-append "@generated by " %generator-path
                      " from RedispatchFunctions.h"))
      ((string=? key "function_redispatch_definitions")
       (map compute-redispatch-function functions))
      (else (error 'unknown-template-key key))))))

;; ---------------------------------------------------------------------------
;; G7: NativeFunctions.h (torchgen gen.py get_native_function_declarations +
;; dest/native_functions.py compute_native_function_declaration)
;; ---------------------------------------------------------------------------

;; The frozen first-appearance order of dispatch keys across the default-flag
;; parse of native_functions.yaml.  get_ns_grouped_kernels iterates
;; backend_indices in this order, which fixes the relative order of kernel
;; declarations for an operator that carries kernels under several dispatch
;; keys (e.g. add: CPU before CUDA before NestedTensorCPU ...).  The scheme's
;; own index accumulation is prepend/assoc-set driven and does not reproduce
;; this order, so the canonical list is pinned here.
(define %native-functions-backend-order
  '("CompositeImplicitAutograd" "CompositeExplicitAutograd" "CPU" "CUDA"
    "Meta" "NestedTensorCPU" "NestedTensorHPU" "NestedTensorCUDA"
    "SparseCPU" "SparseCUDA" "SparseCsrCPU" "SparseCsrCUDA" "SparseCsrMeta"
    "SparseMeta" "MkldnnCPU" "ZeroTensor" "QuantizedCPU" "QuantizedCUDA"
    "CompositeExplicitAutogradNonFunctional" "QuantizedMeta"
    "CompositeImplicitAutogradNestedTensor" "NestedTensorMeta"))

(define (native-functions-backend-rank key)
  (or (list-index (lambda (k) (string=? k key))
                  %native-functions-backend-order)
      1000))

(define (native-meta-name group)
  ;; torchgen api/meta.py name(g): str(g.functional.func.name).replace(".", "_")
  (string-replace-all
   (operator-name->string
    (function-schema-name
     (native-function-func (native-functions-group-functional group))))
   "." "_"))

(define (gen-unstructured f backend-index)
  ;; dest/native_functions.py gen_unstructured with external=False.  Returns the
  ;; "TORCH_API {returns} {kernel}({args});" declaration, or #f when there is no
  ;; kernel metadata or the kernel is a legacy:: one.
  (let ((metadata (api:backend-index-get-kernel f backend-index)))
    (if (or (not metadata)
            (string-contains (backend-metadata-kernel metadata) "legacy::"))
        #f
        (let* ((func (native-function-func f))
               (symint (backend-metadata-supports-symint? metadata))
               (use-const-ref (api:native-function-use-const-ref-context f))
               (use-ilistref (api:native-function-use-ilistref-context f)))
          (string-append
           "TORCH_API "
           (api:ctype-cpp-type
            (api:native-signature-returns-type func symint use-const-ref))
           " " (backend-metadata-kernel metadata) "("
           (string-join
            (map api:binding-decl
                 (api:native-signature-arguments func symint use-const-ref
                                                 use-ilistref))
            ", ")
           ");")))))

(define (gen-structured group backend-index metadata)
  ;; dest/native_functions.py gen_structured with external=False: one multi-line
  ;; struct declaration (the surrounding join/split collapses it back to lines).
  (let ((meta-name (native-meta-name group))
        (out-args (api:structured-impl-arguments group)))
    (list
     (string-append
      "struct TORCH_API structured_" (backend-metadata-kernel metadata)
      " : public at::meta::structured_" meta-name " {\n"
      "void impl(" (string-join (map api:binding-decl out-args) ", ")
      ");\n"
      "};\n"))))

(define (compute-native-function-declaration g backend-index)
  ;; dest/native_functions.py compute_native_function_declaration.
  (if (native-functions-group? g)
      (let ((metadata (api:backend-index-get-kernel-group g backend-index)))
        (if (and metadata (backend-metadata-structured metadata))
            (gen-structured g backend-index metadata)
            (append-map
             (lambda (f)
               (let ((decl (gen-unstructured f backend-index)))
                 (if decl (list decl) '())))
             (native-functions-group-functions g))))
      (let ((decl (gen-unstructured g backend-index)))
        (if decl (list decl) '()))))

(define (ordered-backend-indices indices)
  ;; indices :: ((dispatch-key (op . backend-metadata) ...) ...) in any order;
  ;; reordered to the frozen backend_indices iteration order, each entry wrapped
  ;; as (key kernels device-guard?=#f) for the declaration emitters.
  (map (lambda (entry) (list (car entry) (cdr entry) #f))
       (sort indices
             (lambda (a b)
               (< (native-functions-backend-rank (car a))
                  (native-functions-backend-rank (car b)))))))

(define (get-native-function-declarations grouped backend-indices)
  ;; gen.py get_native_function_declarations: a list of LINES (no newlines) that
  ;; block-substitutes into the template.  There is a single in-tree namespace
  ;; ("at::native"), so the namespace prologue/epilogue are folded in directly;
  ;; the leading "" and trailing "        " mirror the f-string + split(newline)
  ;; and are dropped by the block-substitute.
  (let* ((kernels
          (append-map
           (lambda (f)
             (append-map (lambda (bi)
                           (compute-native-function-declaration f bi))
                         backend-indices))
           grouped))
         (ordered-kernels (delete-duplicates kernels string=?))
         (body (string-append
                "\nnamespace at {\nnamespace native {\n"
                (string-join ordered-kernels "\n")
                "\n} // namespace native\n} // namespace at\n        ")))
    (string-split body #\newline)))

(define %native-functions-template
  (string-append
   "#pragma once\n"
   "\n"
   "// ${generated_comment}\n"
   "\n"
   "#ifdef TORCH_ASSERT_NO_OPERATORS\n"
   "#error This change adds a dependency on native_functions.yaml,            \\\n"
   "  meaning the file will need to be re-compiled every time an operator     \\\n"
   "  is changed or added. Consider if your change would be better placed in  \\\n"
   "  another file, or if a more specific header might achieve the same goal. \\\n"
   "  See NOTE: [Tensor vs. TensorBase]\n"
   "#endif\n"
   "\n"
   "#if defined(AT_PER_OPERATOR_HEADERS) && defined(TORCH_ASSERT_ONLY_METHOD_OPERATORS)\n"
   "#error This change adds a dependency on all pytorch operators, meaning the      \\\n"
   "  file will need to be re-compiled every time an operator is changed or added.  \\\n"
   "  Consider including a specific operator from <ATen/ops/{my_operator}_native.h> \\\n"
   "  and see NOTE [TORCH_ASSERT_ONLY_METHOD_OPERATORS].\n"
   "#endif\n"
   "\n"
   "#include <c10/core/Scalar.h>\n"
   "#include <c10/core/Storage.h>\n"
   "#include <c10/core/TensorOptions.h>\n"
   "#include <c10/util/Deprecated.h>\n"
   "#include <optional>\n"
   "#include <c10/core/QScheme.h>\n"
   "#include <ATen/core/Reduction.h>\n"
   "#include <ATen/core/Tensor.h>\n"
   "#include <tuple>\n"
   "#include <vector>\n"
   "\n"
   "${NativeFunctions_includes}\n"
   "\n"
   "${NativeFunctions_declarations}\n"))

(define* (render-native-functions-h grouped indices
                                    #:key
                                    (includes '("#include <ATen/NativeMetaFunctions.h>"))
                                    (declarations #f))
  ;; indices :: ((dispatch-key (op . backend-metadata) ...) ...) in any order;
  ;; reordered to the frozen backend_indices iteration order.
  (let ((backend-indices (ordered-backend-indices indices)))
    (code-template-substitute
     %native-functions-template
     (lambda (key)
       (cond
        ((string=? key "generated_comment")
         (string-append "@generated by " %generator-path
                        " from NativeFunctions.h"))
        ((string=? key "NativeFunctions_includes") includes)
        ((string=? key "NativeFunctions_declarations")
         (or declarations
             (get-native-function-declarations grouped backend-indices)))
        (else (error 'unknown-template-key key)))))))

;; ---------------------------------------------------------------------------
;; G9: NativeMetaFunctions.h (torchgen gen.compute_meta_function_declaration)
;; ---------------------------------------------------------------------------

(define %native-meta-functions-template
  (string-append
   "#pragma once\n"
   "\n"
   "// ${generated_comment}\n"
   "\n"
   "#include <ATen/core/Tensor.h>\n"
   "#include <ATen/core/IListRef.h>\n"
   "#include <ATen/TensorMeta.h>\n"
   "#include <ATen/TensorIterator.h>\n"
   "\n"
   "${NativeMetaFunctions_includes}\n"
   "\n"
   "namespace at {\n"
   "\n"
   "namespace meta {\n"
   "\n"
   "${NativeMetaFunctions_declarations}\n"
   "\n"
   "} // namespace meta\n"
   "} // namespace at\n"))

;; torchgen api/meta.py name(): str(g.functional.func.name).replace(".", "_")
(define (structured-meta-name group)
  (string-replace-all
   (operator-name->string
    (function-schema-name
     (native-function-func (native-functions-group-functional group))))
   "." "_"))

;; One setter method of the precompute_out struct (compute_meta_function_declaration
;; precomputed branch).  `i` indexes the element being set; `elements` are the
;; precomputed Arguments, `with-types` their NamedCType translations, `params`
;; the upper-cased template parameter names.
(define (compute-precomputed-setter i elements with-types params)
  (let* ((elem (list-ref elements i))
         (nct (list-ref with-types i))
         (return-ty-templates
          (string-join
           (append (take params i) '("true") (drop params (1+ i)))
           ", "))
         (return-ty (string-append "precompute_out<" return-ty-templates ">"))
         (elem-cpp-ty (api:ctype-cpp-type (api:named-ctype-type nct) #t))
         (signature (string-append return-ty " set_" (argument-name elem)
                                   "(" elem-cpp-ty " value)"))
         (assert-msg (string-append "\"" (argument-name elem) " already set\""))
         (assert-stmt (string-append "static_assert(" (list-ref params i)
                                     " == false, " assert-msg ");"))
         (construction-stmts
          (cons (string-append return-ty " ret;")
                (append
                 (map (lambda (j elem2)
                        (if (= i j)
                            (string-append "ret." (argument-name elem2) " = value;")
                            (string-append "ret." (argument-name elem2)
                                           " = this->" (argument-name elem2) ";")))
                      (iota (length elements)) elements)
                 (list "return ret;"))))
         (construction-block (string-join construction-stmts "\n")))
    (string-append
     "\n"
     "                    " signature " {\n"
     "                        " assert-stmt "\n"
     "                        " construction-block "\n"
     "                    }\n"
     "                ")))

;; Returns (values precomputed-decl meta-return-typedef meta-return).
(define (compute-precomputed-decl precomputed)
  (call-with-values
      (lambda () (api:parse-precomputed precomputed))
    (lambda (replace add)
      (let* ((precomputed-values (append (map cdr replace) (list add)))
             (precomputed-elements (append-map identity precomputed-values))
             (template-params (map (lambda (e) (string-upcase (argument-name e)))
                                   precomputed-elements))
             (params-str (string-join
                          (map (lambda (p) (string-append "bool " p " = false"))
                               template-params)
                          ", "))
             (template-decl (string-append "template <" params-str ">"))
             (elements-with-types
              (map (lambda (e) (api:structured-argument-type e (argument-name e)))
                   precomputed-elements))
             (elements-decl
              (string-join
               (map (lambda (nct)
                      (string-append (api:ctype-cpp-type (api:named-ctype-type nct) #t)
                                     " " (api:named-ctype-name nct)))
                    elements-with-types)
               ";\n"))
             (setter-methods-decl
              (string-join
               (map (lambda (i)
                      (compute-precomputed-setter i precomputed-elements
                                                  elements-with-types
                                                  template-params))
                    (iota (length precomputed-elements)))
               "\n"))
             (meta-return-template-params
              (string-join (make-list (length template-params) "true") ", "))
             (meta-return-typedef
              (string-append "using meta_return_ty = precompute_out <"
                             meta-return-template-params ">;"))
             (precomputed-decl
              (string-append
               "\n"
               "                " template-decl "\n"
               "                struct TORCH_API precompute_out {\n"
               "                    " setter-methods-decl "\n"
               "                    " elements-decl ";\n"
               "            };")))
        (values precomputed-decl meta-return-typedef "meta_return_ty")))))

(define (compute-meta-function-declaration g)
  ;; g :: <native-functions-group>.  Returns the structured meta struct text, or
  ;; #f for a non-structured group (mapMaybe drops it).
  (if (not (native-functions-group-structured? g))
      #f
      (let* ((out (native-functions-group-out g))
             (name (structured-meta-name g))
             (args-str (string-join
                        (map api:binding-decl (api:structured-meta-arguments g))
                        ", "))
             (parent-class (or (native-function-structured-inherits out)
                               "at::impl::MetaBase"))
             (precomputed (native-function-precomputed out)))
        (call-with-values
            (lambda ()
              (if precomputed
                  (compute-precomputed-decl precomputed)
                  (values "" "" "void")))
          (lambda (precomputed-decl meta-return-typedef meta-return)
            (string-append
             "struct TORCH_API structured_" name " : public " parent-class " {\n"
             "    " precomputed-decl "\n"
             "    " meta-return-typedef "\n"
             "    " meta-return " meta(" args-str ");\n"
             "};\n"))))))

(define* (render-native-meta-functions-h structured
                                         #:key (includes '()) (declarations #f))
  ;; structured :: the structured native-functions groups, in order.
  (code-template-substitute
   %native-meta-functions-template
   (lambda (key)
     (cond
      ((string=? key "generated_comment")
       (string-append "@generated by " %generator-path
                      " from NativeMetaFunctions.h"))
      ((string=? key "NativeMetaFunctions_includes") includes)
      ((string=? key "NativeMetaFunctions_declarations")
       (or declarations (filter-map compute-meta-function-declaration structured)))
      (else (error 'unknown-template-key key))))))
