SUBDIRS = yaml

moddir = $(GUILE_SITE)/sonic-cross

dist_mod_DATA = api.scm backend-select.scm bootstrap.scm code-template.scm composite-view-copy-kernels.scm core-ir.scm core-sources.scm dispatcher.scm emitter.scm file-manager.scm functionalization.scm generated-functions.scm irregex.scm native-function.scm operators.scm orchestration.scm register-dispatch-key.scm regex.scm schema-parser.scm sha1.scm tensor-body.scm ufunc.scm yaml.scm
