#!/usr/bin/env python3
"""Render RegisterSchema.cpp from the frozen torchgen orchestration.

This mirrors the frozen `gen.py main()` with the default flag set (no
--mps/--xpu/--mtia/--per-operator-headers/--rocm) and a nop selector, but only
materialises the RegisterSchema.cpp artifact.  Every other FileManager write is
recorded-but-not-rendered, so the run stays fast and side-effect free.  The
rendered text is written to stdout, exactly as it would land on disk.

The `generated_comment` prologue is pinned to the canonical generator path
`torchgen/gen.py` by setting `__main__.__file__`, matching how `gen.py` is
invoked in-tree.
"""

import io
import os
import subprocess
import sys
from pathlib import Path

EXPECTED = "41ffbc4a994e058af9fe00ed5caba73fc1033359"


def fail(message):
    raise SystemExit("register-schema oracle: " + message)


root = os.environ.get("SONICCROSS_PYTORCH_ROOT")
if not root:
    fail("set SONICCROSS_PYTORCH_ROOT to the frozen checkout")
root_path = Path(root)
if not (root_path / "torchgen" / "gen.py").is_file():
    fail("checkout does not contain torchgen/gen.py: " + root)
try:
    commit = subprocess.check_output(
        ["git", "-C", str(root_path), "rev-parse", "HEAD"], text=True
    ).strip()
except Exception as exc:
    fail("cannot verify frozen checkout commit: %s" % exc)
if commit != EXPECTED:
    fail("checkout HEAD is %s, expected %s" % (commit, EXPECTED))

sys.path.insert(0, str(root_path))
os.chdir(root_path)

# Pin the generator path so `@generated by ...` is canonical, exactly as when
# torchgen/gen.py is run from the repo root.
import __main__  # noqa: E402

__main__.__file__ = str(root_path / "torchgen" / "gen.py")

import torchgen.utils as utils  # noqa: E402

# The label each FileManager gets is determined by creation order inside main():
# core, cpu, cpu_vec, cuda, ops, aoti, headeronly.
LABELS = ["core", "cpu", "cpu_vec", "cuda", "ops", "aoti", "headeronly"]
_STATE = {"label_idx": 0, "content": None}

_OriginalFileManager = utils.FileManager


class RecordingFileManager(_OriginalFileManager):
    def __init__(self, install_dir, template_dir, dry_run):
        super().__init__(install_dir, template_dir, dry_run)
        self.sc_label = LABELS[_STATE["label_idx"]]
        _STATE["label_idx"] += 1

    def write_with_template(self, filename, template_fn, env_callable):
        filename = Path(filename)
        if filename.is_absolute():
            raise AssertionError(f"filename must be relative: {filename}")
        file = self.install_dir / filename
        if file in self.files:
            raise AssertionError(f"duplicate file write {file}")
        self.files.add(file)
        if filename.as_posix() == "RegisterSchema.cpp":
            _STATE["content"] = self.substitute_with_template(
                template_fn=template_fn, env_callable=env_callable
            )

    def write_sharded_with_template(
        self,
        filename,
        template_fn,
        items,
        *,
        key_fn,
        env_callable,
        num_shards,
        base_env=None,
        sharded_keys=None,
    ):
        # Unsharded, non-RegisterSchema writes are recorded but not rendered.
        filename = Path(filename)
        if filename.is_absolute():
            raise AssertionError(f"filename must be relative: {filename}")


utils.FileManager = RecordingFileManager

import torchgen.gen as gen  # noqa: E402

source_path = str(root_path / "aten" / "src" / "ATen")
install_dir = "/tmp/sc-register-schema-install"
aoti_install_dir = "/tmp/sc-register-schema-aoti-install"

sys.argv = [
    "gen.py",
    "-s",
    source_path,
    "-d",
    install_dir,
    "--aoti-install-dir",
    aoti_install_dir,
]

# gen.main() prints a couple of "not found" diagnostics to stdout when the aoti
# shim headers are absent; capture them so the rendered artifact stays clean.
_stdout = sys.stdout
sys.stdout = io.StringIO()
try:
    gen.main()
finally:
    sys.stdout = _stdout

if _STATE["content"] is None:
    fail("RegisterSchema.cpp was not generated")

sys.stdout.write(_STATE["content"])
